### ISSUE TITLE
How about just detecting persons during training?

### ISSUE THREAD

**Issue by liliangqi** [chenyilun95/tf-cpn#1]
Hi, I'm reading your paper recently and feel it so cool. It is mentioned that you utilized all eighty categories in the dataset to train the detector but only caught person boxes for the follow-up work. I wonder if it is possible to detect person only while ignoring other categories. What are the benefits to detect so match categories?

**Comment by chenyilun95** [comment]
As far as I know, there is no explicit benefit in the final result evaluation using detector for human only. Detecting all categories is just for comparison of results and for convenience.

**Comment by liliangqi** [comment]
Thanks a lot
