### ISSUE TITLE
About coordination recovery

### ISSUE THREAD

**Issue by weleen** [chenyilun95/tf-cpn#13]
when do coordination recovery from the predicted heatmaps, i notice that the result add 2 in x-axis and y-axis, why do this to the coordination? Is this due to the misalignment in prediction?
https://github.com/chenyilun95/tf-cpn/blob/bdc09bbc697283824dd59bd9c29be2f7c3cf51d5/models/COCO.res101.256x192.CPN/mptest.py#L143

**Comment by chenyilun95** [comment]
Yes.
