### ISSUE TITLE
dataset config file confused 

### ISSUE THREAD

**Issue by msunming** [chenyilun95/tf-cpn#14]
why you change the prefix on the stage of train  in COCOAllJoints.py ?  and the dataset config name is 2014 ?

**Comment by chenyilun95** [comment]
Do you mean the prefix of image path? I think I follows our group's general coco path setting, which might has difference with yours.

If you mean the prefix of image file name, I remember that COCO 2017 images are without these prefix and you may need to modify them. Note that COCO2017 train images == COCO2014trainvalminusminival images (which I provide the json file) .

**Comment by msunming** [comment]
ok, thank you response.  close it.

**Comment by chenyilun95** [comment]
It's a historical remaining problem. I think our coco data doesn't include that image. But I'm sure only that one is ignored.

**Comment by msunming** [comment]
OK , thank you.  why ignore the sample when theflag of  iscrowed  is true ?
