### ISSUE TITLE
About data preprocess and data augmentation

### ISSUE THREAD

**Issue by xiashh** [chenyilun95/tf-cpn#19]
I want to know more detail about data prepocessing especially cropping strategy.

**Comment by chenyilun95** [comment]
You can find the summary of our data preprocessing and post-processing strategies in our paper.

**Comment by xiashh** [comment]
Do you use bounding box of ground truth directly without no disturbance during training?

**Comment by chenyilun95** [comment]
Multi-scale training is applied

**Comment by xiashh** [comment]
Yes, I see that in dataset.py. I wonder know why you do not use results of the detector and calculate IOU as  the prediction of instance.

**Comment by chenyilun95** [comment]
I didn’t get it. If you mean we directly train using the detection boxes, I think its performance works like multi scale training and maybe random shifts of the boxes. I think random shifts of boxes can help, which we didn’t try it.
