### ISSUE TITLE
why making the boarder for image in image process？

### ISSUE THREAD

**Issue by lilhope** [chenyilun95/tf-cpn#2]
Hi，I'm quite a newer for human pose estimate, and your work helps me a lot. I'm confused that why you make boarder for the image in the image process, like this code: 
```
bimg = cv2.copyMakeBorder(img, add, add, add, add, borderType=cv2.BORDER_CONSTANT,
                              value=cfg.pixel_means.reshape(-1))
```
It seems to avoid the region with human beyond the image size(e.g. xmin < 0),  you pad the image before cropping the region with human. Did I understand it correctly? If so, crop first then pad the cropped image is another choice?   
Thanks in advance.

**Comment by chenyilun95** [comment]
Yes, you can crop first and pad. Make sure the image doesn't change its aspect ratio.

**Comment by lilhope** [comment]
Thanks，and did you use the resnet-v1 or resnet-v2 as the model backbone？
