### ISSUE TITLE
Question about RefineNet architecture

### ISSUE THREAD

**Issue by happywu** [chenyilun95/tf-cpn#20]
Hi,

I am wondering why 8x upsampling after three bottlenect is used in RefineNet, isn't 8x sampling too harsh?

Thanks.

**Comment by chenyilun95** [comment]
We later concatenate all the feature map of different levels together so they should be same size.

**Comment by happywu** [comment]
@chenyilun95 I mean 8x upsampling could be realized by three 2x sampling, 
thus three (bottleneck + 2x upsampling) instead of three bottleneck + 8x sampling, 
which seems more smooth to me. Did you try this architecture?

**Comment by chenyilun95** [comment]
Bottleneck block doesn't downsample the feature.

**Comment by chenyilun95** [comment]
Oh. I got it. We’ve done some similar architecture without previous FPN feature, which works not as good as this. But not your architecture.

**Comment by happywu** [comment]
Adding FPN feature could lead to good results is reasonable. Thus you didn't do experiments that using the same GlobalNet (FPN), and only differ in how to get high resolution feature maps (how to reach 8x upsampling), right?

**Comment by happywu** [comment]
Got it! Thanks!

**Comment by 7color94** [comment]
I tried it. And it seems that bottleneck + 2x upsampling can not achieves better performance...

**Comment by happywu** [comment]
@7color94 Thanks for the info!
