### ISSUE TITLE
How about the speed?

### ISSUE THREAD

**Issue by yw155** [chenyilun95/tf-cpn#3]
Hi @chenyilun95, thanks for your great work. I would like to ask a question about the speed of CPN. Thanks.

**Comment by chenyilun95** [comment]
Right now we only do some flops analysis in paper. And this code is not written for efficiency and it indeed need some time to make the code quick maybe in C++ programming. In reality the speed depends on the number of detection boxes in one image + network forward + post processing. Thus, you might have a try to run the code and analysis the bottleneck of speed.

**Comment by yw155** [comment]
@chenyilun95, thank you.

**Comment by nvnnghia** [comment]
@yw155 May I ask about speed of this method? Thank you
