### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by ttdd11** [chenyilun95/tf-cpn#31]
Great repo! Do you have any plans to make this compatible with windows?

**Comment by chenyilun95** [comment]
All models are trained and tested in Ubuntu 16.04 system. I haven't tried it in Windows. Sorry for that.

**Comment by ttdd11** [comment]
It took a bit of messing around but I've gotten this to work on Windows. Have you given some thought providing an inference example that doesn't require a coco download?

**Comment by anas-zafar** [comment]
@ttdd11 were you able to set it up on windows?
