### ISSUE TITLE
About heatmap generation

### ISSUE THREAD

**Issue by weleen** [chenyilun95/tf-cpn#32]
https://github.com/chenyilun95/tf-cpn/blob/7c01aba69b8b9ad14fbb36d409f850bafd345dd5/models/COCO.res50.256x192.CPN/dataset.py#L156
I am curious about the generation of heatmap, why multiply 255 here? It seems that the network can not converge  when i remove 255.

**Comment by chenyilun95** [comment]
The prediction heatmap is expected to range in [0...255]. I think it works if you increase learning rate properly and remove 255.
