### ISSUE TITLE
About the provided human detection boxes results

### ISSUE THREAD

**Issue by boyuansun** [chenyilun95/tf-cpn#34]
Hello, could you share the Total Ap and Human AP of the model which produces your provided human detection boxes results. Thanks a lot.

**Comment by chenyilun95** [comment]
The detection result is provided by other person. You can refer the detector https://github.com/zengarden/light_head_rcnn or https://github.com/facebookresearch/Detectron.

**Comment by boyuansun** [comment]
@chenyilun95 Thanks a lot
