### ISSUE TITLE
the influence of detector

### ISSUE THREAD

**Issue by msunming** [chenyilun95/tf-cpn#35]
the performance of human AP from the 57.2 to 62.9  increase extra 1%  in human pose,  will you release the result of 62.9 human detection result for analyze the  importance of detector?

**Comment by msunming** [comment]
3Q. the conclusion may seems conflict in paper about the influence of detector.  Besides , the  nms thr is set one?

**Comment by chenyilun95** [comment]
The detector has a greater but still limited impact on test-dev dataset which we found later. Soft-nms is applied in the given detection result.

**Comment by msunming** [comment]
the resnet50 var name seems not completely  same as tf website, the weight is trained by youself or transform from tf?

**Comment by msunming** [comment]
sorry, its weight same with tf resnet50.

**Comment by msunming** [comment]
In the report, the batchsize also is important. Do you try implement BN cross-gpus and related experiment ?
