### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '.../data/COCO/dets/person_detection_minival411_human553.json'

### ISSUE THREAD

**Issue by sklf** [chenyilun95/tf-cpn#46]
Hello,recently I forked this project and tried to evaluate its performance. But there is an error message when I run 'python3 mptest.py -d 0-1 -r 350'. It says "FileNotFoundError: [Errno 2] No such file or directory: '.../data/COCO/dets/person_detection_minival411_human553.json' ". I can't find this file in the Google Drive. So where can I download this json file?
Thank you very much ^_^

**Comment by chenyilun95** [comment]
https://drive.google.com/drive/folders/1BllF9--dN9uV3FRROcmuIbwNCcn7cCP0?usp=sharing. it's in readme.

**Comment by sklf** [comment]
@chenyilun95 Thank you very much ^_^
