### ISSUE TITLE
error ：no default __reduce__ due to non-trivial __cinit__

### ISSUE THREAD

**Issue by sklf** [chenyilun95/tf-cpn#47]
Hello, I cloned this project recently and tried to evaluate the pretrained model's performance. But when I ran 'python3 mptest.py -d 0-1 -r 350' , I got this error message 
`ran 2337s >> << left 0s 
Traceback (most recent call last):
  File "/share1/home/chunyang/anaconda3/envs/cpn/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/share1/home/chunyang/anaconda3/envs/cpn/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "stringsource", line 2, in pyarrow.lib.Buffer.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
`
So can you guys please tell me how to slove this problem ?

P.S. This error **didn't** come up until the evaluation process was almost done.

**Comment by sklf** [comment]
I used Anaconda to create an environment . The version of Python is 3.6.6 and the version of tensorflow is 1.8.0

**Comment by sklf** [comment]
I set ' dump_method = 1' and the problem is solved

**Comment by DouYishun** [comment]
Hello @sklf , I set `dump_method=0` in lib/tfflat/mp_utils.py and not work. Do you have any other idea?

**Comment by sklf** [comment]
@DouYishun this problem was explained by the author in the "trouble shoot " section. You can find it in the README
