### ISSUE TITLE
how can I run the code in my task,and see the result of my picture or video?

### ISSUE THREAD

**Issue by jycloud** [chenyilun95/tf-cpn#5]
thank you very much

**Comment by chenyilun95** [comment]
I've just add the visualization code in dataset.py to show the groudtruth picture. It saves the visualized gt images by setting vis=True.

**Comment by FightForCS** [comment]
setting vis=True will give the following error
`No module named 'lib'`
I have already run 'make' in lib folder, is there something I was missing? Thx

**Comment by chenyilun95** [comment]
I'm sorry. I mistakes the library path. You can try it now.
