### ISSUE TITLE
A little confuse about "epoch_size".

### ISSUE THREAD

**Issue by GengDavid** [chenyilun95/tf-cpn#6]
Thanks for your great work!
But I'm a little confuse about ```epoch_size = 60000  # include flip * 2, aug * 4, batch * 16``` in [config.py](https://github.com/chenyilun95/tf-cpn/blob/3dc0815e447bca11cecd56108d8f00b5d6ae8942/models/COCO.res50.256x192.CPN/config.py#L25) 
Could you explain about how to get 60000 a little? We know that COCO has about 150k person instances for training. Is there any connection between these two figures?

**Comment by chenyilun95** [comment]
Sorry about that. It's a previous version of code but I forgot to delete the comments. The epoch_size means how many images are trained in one epoch. 60000 is an empirical number. Actually a smaller epoch_size is also acceptable, but in order to get more stable result we just trained longer.

**Comment by GengDavid** [comment]
Got it. Thanks for your explanation.
