### ISSUE TITLE
Which dataset should I download from "http://cocodataset.org/#download" for trainvalminusminival and minival ? 

### ISSUE THREAD

**Issue by YinRui1991** [chenyilun95/tf-cpn#63]
I find the answer that "COCO2017 train images == COCO2014trainvalminusminival images" in #14 , so which dataset is corresponding to "minival"? Thanks.

**Comment by linxiaorui0715** [comment]
OK，Do I need to download a corresponding annotation？

**Comment by linxiaorui0715** [comment]
Thank you so much,could you tell me  trainvalminusminival==?

**Comment by GengDavid** [comment]
2014trainvalminusminival==2017 train
you can use the annotation files provided by the author, but you may need to modify them a little.  Please check them for details.

**Comment by YinRui1991** [comment]
@GengDavid Thank you very much. My question is solved and the cpn codes can run.
