### ISSUE TITLE
bbox is necessary in Test?

### ISSUE THREAD

**Issue by Deicide-LC** [chenyilun95/tf-cpn#79]
Thanks for your great work. It seems that when I  test some targets in a picture, I must provides their bbox information.Is that true?
PS: I hope you can show us a script which can visualize the test result，thank you very much

**Comment by chenyilun95** [comment]
Yes, most top-down approaches require a 2D detector.

**Comment by Deicide-LC** [comment]
@chenyilun95 Got it,thanks for your reply
